# 配置数据源信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pest_identify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: 123456


# 项目资源图片文件目录配置
pest-image-path:
  prefix: C:\src\Pests Identification\


# 七牛云上传密钥
qiniu:
  access_key: replace_it_with_yours_access_key
  secret_key: replace_it_with_yours_secret_key

# 开始debug模式
debug: true