# web访问端口号  8088
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  maxHttpHeaderSize: 50MB


# 配置数据源信息
spring:
  profiles:
    active: prod
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1


# mybatis 配置
mybatis:
  type-aliases-package: com.jsjds.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件


# 通用 Mapper 配置
mapper:
  mappers: com.jsjds.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

# 项目资源图片文件目录配置
pest-image-path:
  defaultAlbumName: "未分类"
  oss-domain: "http://resource.taibai.cloud/"
